"""
store_capture.py — our own session capture store. Lives alongside claude-mem
during the dual-write period (Phase B); becomes the source of truth in Phase D.

Schema:
  sessions(id PK, project, cwd, started_at, ended_at, status, first_prompt, prompt_count)
  prompts(id PK, session_id FK, ts, text)

The DB is at ~/.claude-kb/data.db. Schema is created on first use.
"""
from __future__ import annotations

import json
import os
import sqlite3
import threading
import time
from typing import Optional

DATA_DIR = os.path.expanduser("~/.claude-kb")
DB_PATH = os.path.join(DATA_DIR, "data.db")

_SCHEMA = """
CREATE TABLE IF NOT EXISTS sessions (
  id           TEXT PRIMARY KEY,
  project      TEXT,
  cwd          TEXT,
  started_at   INTEGER NOT NULL,
  ended_at     INTEGER,
  status       TEXT DEFAULT 'active',
  first_prompt TEXT,
  prompt_count INTEGER DEFAULT 0,
  label        TEXT,        -- Phase C: kebab label (filled when observations generated)
  summary      TEXT         -- Phase C: 1-2 sentence session summary
);
CREATE INDEX IF NOT EXISTS idx_sessions_started ON sessions(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project ON sessions(project);

CREATE TABLE IF NOT EXISTS prompts (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  ts         INTEGER NOT NULL,
  text       TEXT NOT NULL,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_prompts_session ON prompts(session_id, ts);

-- Phase C: topical observations, generated by DeepSeek per session.
-- These are *ours* — they use domain-specific tags (acronyms, identifiers, file names)
-- instead of claude-mem's generic 'how-it-works' / 'what-changed' concepts.
CREATE TABLE IF NOT EXISTS observations (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id  TEXT NOT NULL,
  ord         INTEGER NOT NULL,                -- index within the session
  type        TEXT NOT NULL,                   -- discovery|change|bugfix|decision|refactor|feature
  title       TEXT NOT NULL,
  text        TEXT,
  tags        TEXT NOT NULL DEFAULT '[]',      -- JSON array of topical tokens
  created_at  INTEGER NOT NULL,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_observations_session ON observations(session_id, ord);
CREATE INDEX IF NOT EXISTS idx_observations_type    ON observations(type);

-- Phase E (tool-call capture): one row per PostToolUse event from Claude Code,
-- queued for the background summarizer to roll up into observations.
CREATE TABLE IF NOT EXISTS tool_calls (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id    TEXT NOT NULL,
  ts            INTEGER NOT NULL,
  tool_name     TEXT NOT NULL,
  tool_input    TEXT,                            -- truncated JSON
  tool_response TEXT,                            -- truncated head+tail
  files         TEXT NOT NULL DEFAULT '[]',      -- JSON array of touched paths
  status        TEXT NOT NULL DEFAULT 'pending', -- pending|processed|failed
  processed_at  INTEGER,
  observation_id INTEGER,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tool_calls_session_ts ON tool_calls(session_id, ts);
CREATE INDEX IF NOT EXISTS idx_tool_calls_status     ON tool_calls(status);

-- Files-touched index, populated alongside tool_calls. Lets recall boost
-- sessions that touched the file the user is asking about right now.
CREATE TABLE IF NOT EXISTS session_files (
  session_id  TEXT NOT NULL,
  path        TEXT NOT NULL,
  kind        TEXT NOT NULL,                    -- read|edited|mentioned
  first_seen  INTEGER NOT NULL,
  last_seen   INTEGER NOT NULL,
  count       INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (session_id, path, kind),
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_session_files_path ON session_files(path);

-- Phase D (cross-session lessons): distilled patterns that recur across many
-- observations. Populated by /api/lessons/distill.
CREATE TABLE IF NOT EXISTS lessons (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  title              TEXT NOT NULL,
  text               TEXT NOT NULL,
  tags               TEXT NOT NULL DEFAULT '[]',  -- JSON array
  source_session_ids TEXT NOT NULL DEFAULT '[]',  -- JSON array of session UUIDs
  evidence_count     INTEGER NOT NULL DEFAULT 0,
  first_seen         INTEGER NOT NULL,
  last_seen          INTEGER NOT NULL,
  superseded_by      INTEGER,
  created_at         INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_lessons_last_seen ON lessons(last_seen DESC);

-- Knowledge ingest: the hand-authored auto-memory under
-- ~/.claude/projects/*/memory/*.md (one fact per file). Mirrored here so the
-- shared record corpus (store.py) can embed + search them alongside
-- observations and lessons. Synced from disk by memory_ingest.scan(); mtime +
-- content_hash gate the writes so an unchanged file is a no-op.
CREATE TABLE IF NOT EXISTS memory_facts (
  id           TEXT PRIMARY KEY,            -- stable "<project>::<name>"
  project      TEXT,
  source_path  TEXT NOT NULL,
  name         TEXT,
  mem_type     TEXT,                        -- user|feedback|project|reference
  description  TEXT,
  text         TEXT NOT NULL,               -- the fact (file body)
  tags         TEXT NOT NULL DEFAULT '[]',  -- JSON array
  content_hash TEXT NOT NULL,               -- sha1(body) — drives the re-embed id
  mtime        INTEGER NOT NULL,            -- source file mtime (epoch-ms)
  updated_at   INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_memory_facts_project ON memory_facts(project);
"""

# Lightweight migrations — old DBs with the original schema get the new columns added.
_MIGRATIONS = [
    "ALTER TABLE sessions ADD COLUMN label TEXT",
    "ALTER TABLE sessions ADD COLUMN summary TEXT",
]


class CaptureStore:
    """Thread-safe SQLite-backed capture store. One process, many writer threads."""

    def __init__(self, db_path: str = DB_PATH):
        os.makedirs(os.path.dirname(db_path), exist_ok=True)
        self.db_path = db_path
        self._lock = threading.Lock()
        self._init_schema()

    def _conn(self) -> sqlite3.Connection:
        c = sqlite3.connect(self.db_path, isolation_level=None)
        c.execute("PRAGMA journal_mode=WAL;")
        c.execute("PRAGMA foreign_keys=ON;")
        c.row_factory = sqlite3.Row
        return c

    def _init_schema(self) -> None:
        with self._lock, self._conn() as c:
            c.executescript(_SCHEMA)
            # Best-effort lightweight migrations for DBs created before Phase C.
            for stmt in _MIGRATIONS:
                try:
                    c.execute(stmt)
                except sqlite3.OperationalError:
                    pass  # column already exists

    def session_start(self, session_id: str, project: Optional[str],
                      cwd: Optional[str], started_at: Optional[int] = None) -> None:
        """Idempotent: SessionStart fires for resumes too; we INSERT OR IGNORE."""
        ts = started_at or int(time.time() * 1000)
        with self._lock, self._conn() as c:
            c.execute(
                "INSERT OR IGNORE INTO sessions (id, project, cwd, started_at, status) "
                "VALUES (?, ?, ?, ?, 'active')",
                (session_id, project, cwd, ts),
            )

    def record_prompt(self, session_id: str, text: str,
                      project: Optional[str] = None, cwd: Optional[str] = None,
                      ts: Optional[int] = None) -> None:
        """Append a prompt to its session. Auto-creates the session if missing
        (e.g. UserPromptSubmit arrives before SessionStart on a resumed session)
        and stamps first_prompt the first time we see one."""
        ts = ts or int(time.time() * 1000)
        with self._lock, self._conn() as c:
            c.execute(
                "INSERT OR IGNORE INTO sessions (id, project, cwd, started_at, status) "
                "VALUES (?, ?, ?, ?, 'active')",
                (session_id, project, cwd, ts),
            )
            c.execute(
                "INSERT INTO prompts (session_id, ts, text) VALUES (?, ?, ?)",
                (session_id, ts, text),
            )
            c.execute(
                "UPDATE sessions SET "
                "  first_prompt = COALESCE(first_prompt, ?), "
                "  prompt_count = prompt_count + 1 "
                "WHERE id = ?",
                (text, session_id),
            )

    def session_end(self, session_id: str, ts: Optional[int] = None) -> None:
        ts = ts or int(time.time() * 1000)
        with self._lock, self._conn() as c:
            c.execute(
                "UPDATE sessions SET ended_at = ?, status = 'completed' WHERE id = ?",
                (ts, session_id),
            )

    # --- read helpers (used by /api/capture endpoints) ---
    def stats(self) -> dict:
        with self._conn() as c:
            n_sess = c.execute("SELECT COUNT(*) FROM sessions").fetchone()[0]
            n_prompts = c.execute("SELECT COUNT(*) FROM prompts").fetchone()[0]
            n_active = c.execute("SELECT COUNT(*) FROM sessions WHERE status='active'").fetchone()[0]
            latest = c.execute(
                "SELECT id, project, started_at, first_prompt FROM sessions "
                "ORDER BY started_at DESC LIMIT 5"
            ).fetchall()
        return {
            "db_path": self.db_path,
            "sessions": n_sess,
            "prompts": n_prompts,
            "active": n_active,
            "latest": [dict(r) for r in latest],
        }

    def list_sessions(self, limit: int = 50) -> list[dict]:
        with self._conn() as c:
            rows = c.execute(
                "SELECT id, project, cwd, started_at, ended_at, status, "
                "       first_prompt, prompt_count, label, summary "
                "FROM sessions ORDER BY started_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [dict(r) for r in rows]

    # ----- Phase C helpers -----
    def get_session(self, session_id: str) -> Optional[dict]:
        with self._conn() as c:
            r = c.execute("SELECT * FROM sessions WHERE id = ?", (session_id,)).fetchone()
        return dict(r) if r else None

    def prompts_for(self, session_id: str, limit: int = 200) -> list[str]:
        with self._conn() as c:
            rows = c.execute(
                "SELECT text FROM prompts WHERE session_id = ? ORDER BY ts LIMIT ?",
                (session_id, limit),
            ).fetchall()
        return [r["text"] for r in rows]

    def set_session_clarification(self, session_id: str, label: Optional[str],
                                  summary: Optional[str]) -> None:
        with self._lock, self._conn() as c:
            c.execute(
                "UPDATE sessions SET label = COALESCE(?, label), summary = COALESCE(?, summary) "
                "WHERE id = ?",
                (label, summary, session_id),
            )

    def replace_observations(self, session_id: str, observations: list[dict]) -> int:
        """Drop existing observations for this session and insert the new ones.
        Each observation: {type, title, text, tags: [str]}."""
        now = int(time.time() * 1000)
        with self._lock, self._conn() as c:
            c.execute("DELETE FROM observations WHERE session_id = ?", (session_id,))
            for i, o in enumerate(observations):
                c.execute(
                    "INSERT INTO observations (session_id, ord, type, title, text, tags, created_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (
                        session_id, i,
                        (o.get("type") or "discovery").lower(),
                        (o.get("title") or "").strip()[:200],
                        (o.get("text") or "").strip(),
                        json.dumps(list(o.get("tags") or [])[:8]),
                        now,
                    ),
                )
            return len(observations)

    def observations_for(self, session_id: str) -> list[dict]:
        with self._conn() as c:
            rows = c.execute(
                "SELECT id, ord, type, title, text, tags, created_at "
                "FROM observations WHERE session_id = ? ORDER BY ord",
                (session_id,),
            ).fetchall()
        out = []
        for r in rows:
            d = dict(r)
            try:
                d["tags"] = json.loads(d["tags"] or "[]")
            except json.JSONDecodeError:
                d["tags"] = []
            out.append(d)
        return out

    def sessions_needing_observations(self, limit: int = 1000) -> list[str]:
        """For backfill: session ids that have prompts but no observations yet."""
        with self._conn() as c:
            rows = c.execute(
                "SELECT s.id FROM sessions s "
                "WHERE s.prompt_count > 0 "
                "  AND NOT EXISTS (SELECT 1 FROM observations o WHERE o.session_id = s.id) "
                "ORDER BY s.started_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [r["id"] for r in rows]

    def import_legacy_session(self, session_id: str, project: Optional[str],
                              started_at: int, first_prompt: Optional[str],
                              prompts: list[tuple[int, str]]) -> None:
        """Seed a session + its prompts from an external source (e.g. claude-mem).
        Used by the backfill so Phase C has real material to generate against
        before new sessions accumulate naturally."""
        with self._lock, self._conn() as c:
            c.execute(
                "INSERT OR IGNORE INTO sessions (id, project, started_at, status, first_prompt, prompt_count) "
                "VALUES (?, ?, ?, 'completed', ?, 0)",
                (session_id, project, started_at, first_prompt),
            )
            # Only insert prompts if this session has none yet (idempotent backfill)
            existing = c.execute(
                "SELECT COUNT(*) FROM prompts WHERE session_id = ?", (session_id,)
            ).fetchone()[0]
            if existing == 0 and prompts:
                c.executemany(
                    "INSERT INTO prompts (session_id, ts, text) VALUES (?, ?, ?)",
                    [(session_id, ts, text) for ts, text in prompts],
                )
                c.execute(
                    "UPDATE sessions SET prompt_count = ? WHERE id = ?",
                    (len(prompts), session_id),
                )

    # ─────────────────────────────────────────────────────────────────────────
    # Phase E: tool-call capture + file index. PostToolUse hook calls
    # record_tool_call(); the background summarizer drains pending rows via
    # sessions_with_pending_tools + pop_pending_tools + mark_tools_processed.
    # ─────────────────────────────────────────────────────────────────────────
    def record_tool_call(self, session_id: str, ts: int, tool_name: str,
                         tool_input: Optional[str], tool_response: Optional[str],
                         files: list[str], kind: str = "read",
                         project: Optional[str] = None, cwd: Optional[str] = None) -> int:
        """Append a tool-call row and upsert session_files for each path.
        Creates the session shell if missing (PostToolUse can fire before any
        UserPromptSubmit hook registered the session — same defensive insert
        as record_prompt). Returns the new tool_calls row id."""
        with self._lock, self._conn() as c:
            c.execute(
                "INSERT OR IGNORE INTO sessions (id, project, cwd, started_at, status) "
                "VALUES (?, ?, ?, ?, 'active')",
                (session_id, project, cwd, ts),
            )
            cur = c.execute(
                "INSERT INTO tool_calls "
                "  (session_id, ts, tool_name, tool_input, tool_response, files, status) "
                "VALUES (?, ?, ?, ?, ?, ?, 'pending')",
                (session_id, ts, tool_name, tool_input, tool_response,
                 json.dumps(list(files or [])[:32])),
            )
            tc_id = cur.lastrowid
            for f in (files or []):
                if not f or len(f) > 500:
                    continue
                c.execute(
                    "INSERT INTO session_files (session_id, path, kind, first_seen, last_seen, count) "
                    "VALUES (?, ?, ?, ?, ?, 1) "
                    "ON CONFLICT(session_id, path, kind) DO UPDATE SET "
                    "  last_seen = excluded.last_seen, "
                    "  count = session_files.count + 1",
                    (session_id, f, kind, ts, ts),
                )
            return tc_id

    def sessions_with_pending_tools(self, min_age_s: int = 300,
                                    max_sessions: int = 20) -> list[str]:
        """Session ids whose oldest pending tool-call has aged past min_age_s
        (so we batch by session and don't summarize mid-burst). Returned in
        order of oldest-pending-first so long-idle sessions drain first."""
        cutoff = int(time.time() * 1000) - min_age_s * 1000
        with self._conn() as c:
            rows = c.execute(
                "SELECT session_id, MIN(ts) AS oldest "
                "FROM tool_calls WHERE status = 'pending' "
                "GROUP BY session_id HAVING oldest <= ? "
                "ORDER BY oldest ASC LIMIT ?",
                (cutoff, max_sessions),
            ).fetchall()
        return [r["session_id"] for r in rows]

    def pop_pending_tools(self, session_id: str, limit: int = 50) -> list[dict]:
        """Return up to `limit` pending tool-call rows for this session,
        oldest-first. Caller marks them processed once the summarizer is done
        (atomicity isn't critical — duplicate processing would just produce
        duplicate observations on retry, and we dedupe by content via the
        existing replace_observations path)."""
        with self._conn() as c:
            rows = c.execute(
                "SELECT id, ts, tool_name, tool_input, tool_response, files "
                "FROM tool_calls WHERE session_id = ? AND status = 'pending' "
                "ORDER BY ts ASC LIMIT ?",
                (session_id, limit),
            ).fetchall()
        out = []
        for r in rows:
            d = dict(r)
            try:
                d["files"] = json.loads(d["files"] or "[]")
            except json.JSONDecodeError:
                d["files"] = []
            out.append(d)
        return out

    def mark_tools_processed(self, ids: list[int], observation_id: Optional[int] = None) -> int:
        if not ids:
            return 0
        now = int(time.time() * 1000)
        placeholders = ",".join("?" for _ in ids)
        with self._lock, self._conn() as c:
            c.execute(
                f"UPDATE tool_calls "
                f"SET status = 'processed', processed_at = ?, observation_id = ? "
                f"WHERE id IN ({placeholders})",
                (now, observation_id, *ids),
            )
            return len(ids)

    def files_for_session(self, session_id: str, limit: int = 50) -> list[dict]:
        with self._conn() as c:
            rows = c.execute(
                "SELECT path, kind, count, last_seen FROM session_files "
                "WHERE session_id = ? ORDER BY count DESC, last_seen DESC LIMIT ?",
                (session_id, limit),
            ).fetchall()
        return [dict(r) for r in rows]

    def sessions_for_file(self, path: str, limit: int = 20) -> list[dict]:
        """Sessions that touched `path`, most-recent-first. Used by the
        file-aware recall boost AND the by-file MCP tool."""
        with self._conn() as c:
            rows = c.execute(
                "SELECT sf.session_id, sf.kind, sf.count, sf.last_seen, "
                "       s.project, s.label, s.summary "
                "FROM session_files sf LEFT JOIN sessions s ON s.id = sf.session_id "
                "WHERE sf.path = ? OR sf.path LIKE ? "
                "ORDER BY sf.last_seen DESC LIMIT ?",
                (path, f"%/{path}", limit),
            ).fetchall()
        return [dict(r) for r in rows]

    def session_file_overlap(self, session_id: str, paths: list[str]) -> int:
        """How many of `paths` this session has in session_files. Lookup is
        bounded by the size of `paths` (small; the recall handler extracts
        only a few file-shaped tokens from the query). Suffix-match the
        same way sessions_for_file does so a bare basename matches a full path."""
        if not paths:
            return 0
        clauses = " OR ".join(["sf.path = ? OR sf.path LIKE ?"] * len(paths))
        args: list = [session_id]
        for p in paths:
            args.extend([p, f"%/{p}"])
        with self._conn() as c:
            row = c.execute(
                f"SELECT COUNT(DISTINCT sf.path) AS n FROM session_files sf "
                f"WHERE sf.session_id = ? AND ({clauses})",
                args,
            ).fetchone()
        return int(row["n"] or 0)

    def session_file_counts(self) -> dict[str, int]:
        """Map of session_id -> distinct files touched, for the card chip."""
        with self._conn() as c:
            rows = c.execute(
                "SELECT session_id, COUNT(DISTINCT path) AS n "
                "FROM session_files GROUP BY session_id"
            ).fetchall()
        return {r["session_id"]: int(r["n"]) for r in rows}

    def append_observations(self, session_id: str, observations: list[dict]) -> int:
        """Append observations to a session WITHOUT wiping existing ones.
        Used by the background tool-call summarizer (the per-prompt /api/observe
        path still uses replace_observations for idempotent regeneration)."""
        if not observations:
            return 0
        now = int(time.time() * 1000)
        with self._lock, self._conn() as c:
            base = c.execute(
                "SELECT COALESCE(MAX(ord), -1) + 1 FROM observations WHERE session_id = ?",
                (session_id,),
            ).fetchone()[0]
            for i, o in enumerate(observations):
                c.execute(
                    "INSERT INTO observations (session_id, ord, type, title, text, tags, created_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (
                        session_id, base + i,
                        (o.get("type") or "discovery").lower(),
                        (o.get("title") or "").strip()[:200],
                        (o.get("text") or "").strip(),
                        json.dumps(list(o.get("tags") or [])[:8]),
                        now,
                    ),
                )
            return len(observations)

    # ─────────────────────────────────────────────────────────────────────────
    # Phase D: cross-session lessons rollup.
    # ─────────────────────────────────────────────────────────────────────────
    def replace_lessons(self, lessons: list[dict]) -> int:
        """Replace the entire lessons table contents. /api/lessons/distill is
        idempotent — running it again with the same observation corpus yields
        the same (LLM-cached) lessons, so a wipe-and-rewrite is the simplest
        consistent strategy."""
        now = int(time.time() * 1000)
        with self._lock, self._conn() as c:
            c.execute("DELETE FROM lessons")
            for L in lessons:
                sids = list(L.get("source_session_ids") or [])
                c.execute(
                    "INSERT INTO lessons "
                    "  (title, text, tags, source_session_ids, evidence_count, "
                    "   first_seen, last_seen, created_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    (
                        (L.get("title") or "").strip()[:200],
                        (L.get("text") or "").strip(),
                        json.dumps(list(L.get("tags") or [])[:8]),
                        json.dumps(sids[:32]),
                        int(L.get("evidence_count") or len(sids)),
                        int(L.get("first_seen") or now),
                        int(L.get("last_seen") or now),
                        now,
                    ),
                )
            return len(lessons)

    def merge_lessons(self, lessons: list[dict]) -> int:
        """Upsert lessons by title (case-insensitive). For an existing title:
        refresh text/tags, bump last_seen, and union source_session_ids (so
        evidence accumulates). For a new title: insert. Crucially this NEVER
        deletes — a durable lesson the distiller didn't re-derive this run
        survives, unlike replace_lessons() which wipes the table. Returns the
        number of lessons written (inserted + updated)."""
        if not lessons:
            return 0
        now = int(time.time() * 1000)
        with self._lock, self._conn() as c:
            existing: dict[str, tuple] = {}
            for r in c.execute(
                "SELECT id, title, source_session_ids, first_seen FROM lessons"
            ).fetchall():
                existing[(r["title"] or "").strip().lower()] = (
                    r["id"], r["source_session_ids"], r["first_seen"])
            written = 0
            for L in lessons:
                title = (L.get("title") or "").strip()
                if not title:
                    continue
                key = title.lower()
                new_sids = [s for s in (L.get("source_session_ids") or [])
                            if isinstance(s, str)]
                tags = json.dumps(list(L.get("tags") or [])[:8])
                text = (L.get("text") or "").strip()
                last_seen = int(L.get("last_seen") or now)
                if key in existing:
                    lid, raw_sids, first_seen = existing[key]
                    try:
                        old_sids = json.loads(raw_sids or "[]")
                    except json.JSONDecodeError:
                        old_sids = []
                    merged = list(dict.fromkeys([*old_sids, *new_sids]))[:32]
                    c.execute(
                        "UPDATE lessons SET text = ?, tags = ?, "
                        "  source_session_ids = ?, evidence_count = ?, last_seen = ? "
                        "WHERE id = ?",
                        (text, tags, json.dumps(merged), len(merged), last_seen, lid),
                    )
                else:
                    c.execute(
                        "INSERT INTO lessons "
                        "  (title, text, tags, source_session_ids, evidence_count, "
                        "   first_seen, last_seen, created_at) "
                        "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                        (title[:200], text, tags, json.dumps(new_sids[:32]),
                         int(L.get("evidence_count") or len(new_sids)),
                         int(L.get("first_seen") or now), last_seen, now),
                    )
                written += 1
            return written

    def list_lessons(self, tag: Optional[str] = None, limit: int = 50) -> list[dict]:
        with self._conn() as c:
            if tag:
                rows = c.execute(
                    "SELECT * FROM lessons "
                    "WHERE tags LIKE ? "
                    "ORDER BY last_seen DESC LIMIT ?",
                    (f'%"{tag}"%', limit),
                ).fetchall()
            else:
                rows = c.execute(
                    "SELECT * FROM lessons ORDER BY last_seen DESC LIMIT ?",
                    (limit,),
                ).fetchall()
        out = []
        for r in rows:
            d = dict(r)
            for k in ("tags", "source_session_ids"):
                try:
                    d[k] = json.loads(d[k] or "[]")
                except json.JSONDecodeError:
                    d[k] = []
            out.append(d)
        return out

    # ─────────────────────────────────────────────────────────────────────────
    # Knowledge ingest: auto-memory facts synced from
    # ~/.claude/projects/*/memory/*.md by memory_ingest.scan().
    # ─────────────────────────────────────────────────────────────────────────
    def distinct_projects(self) -> list[str]:
        """Project names seen in the sessions table. memory_ingest uses these to
        map a memory directory slug back to its real project name via suffix
        match (e.g. '-home-erick-dev-claude-kb' -> 'claude-kb')."""
        with self._conn() as c:
            rows = c.execute(
                "SELECT DISTINCT project FROM sessions WHERE project IS NOT NULL AND project != ''"
            ).fetchall()
        return [r["project"] for r in rows]

    def upsert_memory_fact(self, fact: dict) -> str:
        """Insert/update one memory fact. Returns 'inserted' | 'updated' |
        'unchanged'. An unchanged file (same mtime AND content_hash) is a no-op
        so a re-scan doesn't bump updated_at and trigger needless re-embeds."""
        now = int(time.time() * 1000)
        fid = fact["id"]
        with self._lock, self._conn() as c:
            existing = c.execute(
                "SELECT mtime, content_hash FROM memory_facts WHERE id = ?", (fid,)
            ).fetchone()
            if existing and existing["mtime"] == int(fact["mtime"]) \
                    and existing["content_hash"] == fact["content_hash"]:
                return "unchanged"
            c.execute(
                "INSERT INTO memory_facts "
                "  (id, project, source_path, name, mem_type, description, text, "
                "   tags, content_hash, mtime, updated_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) "
                "ON CONFLICT(id) DO UPDATE SET "
                "  project=excluded.project, source_path=excluded.source_path, "
                "  name=excluded.name, mem_type=excluded.mem_type, "
                "  description=excluded.description, text=excluded.text, "
                "  tags=excluded.tags, content_hash=excluded.content_hash, "
                "  mtime=excluded.mtime, updated_at=excluded.updated_at",
                (
                    fid, fact.get("project"), fact["source_path"],
                    fact.get("name"), fact.get("mem_type"), fact.get("description"),
                    fact.get("text") or "",
                    json.dumps(list(fact.get("tags") or [])[:8]),
                    fact["content_hash"], int(fact["mtime"]), now,
                ),
            )
            return "updated" if existing else "inserted"

    def prune_memory_facts(self, keep_ids: list[str]) -> int:
        """Delete memory_facts whose source file no longer exists on disk
        (i.e. id not in keep_ids). Returns rows removed."""
        with self._lock, self._conn() as c:
            if not keep_ids:
                cur = c.execute("DELETE FROM memory_facts")
                return cur.rowcount or 0
            placeholders = ",".join("?" for _ in keep_ids)
            cur = c.execute(
                f"DELETE FROM memory_facts WHERE id NOT IN ({placeholders})",
                keep_ids,
            )
            return cur.rowcount or 0

    def list_memory_facts(self, mem_type: Optional[str] = None,
                          limit: int = 200) -> list[dict]:
        with self._conn() as c:
            if mem_type:
                rows = c.execute(
                    "SELECT * FROM memory_facts WHERE mem_type = ? "
                    "ORDER BY updated_at DESC LIMIT ?",
                    (mem_type, limit),
                ).fetchall()
            else:
                rows = c.execute(
                    "SELECT * FROM memory_facts ORDER BY updated_at DESC LIMIT ?",
                    (limit,),
                ).fetchall()
        out = []
        for r in rows:
            d = dict(r)
            try:
                d["tags"] = json.loads(d["tags"] or "[]")
            except json.JSONDecodeError:
                d["tags"] = []
            out.append(d)
        return out

    def observations_since(self, since_ms: int, limit: int = 5000) -> list[dict]:
        """Window of observations for the lessons distiller."""
        with self._conn() as c:
            rows = c.execute(
                "SELECT o.session_id, o.title, o.text, o.tags, o.type, o.created_at, "
                "       s.project, s.label "
                "FROM observations o LEFT JOIN sessions s ON s.id = o.session_id "
                "WHERE o.created_at >= ? "
                "ORDER BY o.created_at DESC LIMIT ?",
                (since_ms, limit),
            ).fetchall()
        out = []
        for r in rows:
            d = dict(r)
            try:
                d["tags"] = json.loads(d["tags"] or "[]")
            except json.JSONDecodeError:
                d["tags"] = []
            out.append(d)
        return out
