"""
store_capture.py — our own session capture store. Lives alongside claude-mem
during the dual-write period (Phase B); becomes the source of truth in Phase D.

Schema:
  sessions(id PK, project, cwd, started_at, ended_at, status, first_prompt, prompt_count)
  prompts(id PK, session_id FK, ts, text)

The DB is at ~/.claude-kb/data.db. Schema is created on first use.
"""
from __future__ import annotations

import json
import os
import sqlite3
import threading
import time
from typing import Optional

DATA_DIR = os.path.expanduser("~/.claude-kb")
DB_PATH = os.path.join(DATA_DIR, "data.db")

_SCHEMA = """
CREATE TABLE IF NOT EXISTS sessions (
  id           TEXT PRIMARY KEY,
  project      TEXT,
  cwd          TEXT,
  started_at   INTEGER NOT NULL,
  ended_at     INTEGER,
  status       TEXT DEFAULT 'active',
  first_prompt TEXT,
  prompt_count INTEGER DEFAULT 0,
  label        TEXT,        -- Phase C: kebab label (filled when observations generated)
  summary      TEXT         -- Phase C: 1-2 sentence session summary
);
CREATE INDEX IF NOT EXISTS idx_sessions_started ON sessions(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project ON sessions(project);

CREATE TABLE IF NOT EXISTS prompts (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  ts         INTEGER NOT NULL,
  text       TEXT NOT NULL,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_prompts_session ON prompts(session_id, ts);

-- Phase C: topical observations, generated by DeepSeek per session.
-- These are *ours* — they use domain-specific tags (acronyms, identifiers, file names)
-- instead of claude-mem's generic 'how-it-works' / 'what-changed' concepts.
CREATE TABLE IF NOT EXISTS observations (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id  TEXT NOT NULL,
  ord         INTEGER NOT NULL,                -- index within the session
  type        TEXT NOT NULL,                   -- discovery|change|bugfix|decision|refactor|feature
  title       TEXT NOT NULL,
  text        TEXT,
  tags        TEXT NOT NULL DEFAULT '[]',      -- JSON array of topical tokens
  created_at  INTEGER NOT NULL,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_observations_session ON observations(session_id, ord);
CREATE INDEX IF NOT EXISTS idx_observations_type    ON observations(type);
"""

# Lightweight migrations — old DBs with the original schema get the new columns added.
_MIGRATIONS = [
    "ALTER TABLE sessions ADD COLUMN label TEXT",
    "ALTER TABLE sessions ADD COLUMN summary TEXT",
]


class CaptureStore:
    """Thread-safe SQLite-backed capture store. One process, many writer threads."""

    def __init__(self, db_path: str = DB_PATH):
        os.makedirs(os.path.dirname(db_path), exist_ok=True)
        self.db_path = db_path
        self._lock = threading.Lock()
        self._init_schema()

    def _conn(self) -> sqlite3.Connection:
        c = sqlite3.connect(self.db_path, isolation_level=None)
        c.execute("PRAGMA journal_mode=WAL;")
        c.execute("PRAGMA foreign_keys=ON;")
        c.row_factory = sqlite3.Row
        return c

    def _init_schema(self) -> None:
        with self._lock, self._conn() as c:
            c.executescript(_SCHEMA)
            # Best-effort lightweight migrations for DBs created before Phase C.
            for stmt in _MIGRATIONS:
                try:
                    c.execute(stmt)
                except sqlite3.OperationalError:
                    pass  # column already exists

    def session_start(self, session_id: str, project: Optional[str],
                      cwd: Optional[str], started_at: Optional[int] = None) -> None:
        """Idempotent: SessionStart fires for resumes too; we INSERT OR IGNORE."""
        ts = started_at or int(time.time() * 1000)
        with self._lock, self._conn() as c:
            c.execute(
                "INSERT OR IGNORE INTO sessions (id, project, cwd, started_at, status) "
                "VALUES (?, ?, ?, ?, 'active')",
                (session_id, project, cwd, ts),
            )

    def record_prompt(self, session_id: str, text: str,
                      project: Optional[str] = None, cwd: Optional[str] = None,
                      ts: Optional[int] = None) -> None:
        """Append a prompt to its session. Auto-creates the session if missing
        (e.g. UserPromptSubmit arrives before SessionStart on a resumed session)
        and stamps first_prompt the first time we see one."""
        ts = ts or int(time.time() * 1000)
        with self._lock, self._conn() as c:
            c.execute(
                "INSERT OR IGNORE INTO sessions (id, project, cwd, started_at, status) "
                "VALUES (?, ?, ?, ?, 'active')",
                (session_id, project, cwd, ts),
            )
            c.execute(
                "INSERT INTO prompts (session_id, ts, text) VALUES (?, ?, ?)",
                (session_id, ts, text),
            )
            c.execute(
                "UPDATE sessions SET "
                "  first_prompt = COALESCE(first_prompt, ?), "
                "  prompt_count = prompt_count + 1 "
                "WHERE id = ?",
                (text, session_id),
            )

    def session_end(self, session_id: str, ts: Optional[int] = None) -> None:
        ts = ts or int(time.time() * 1000)
        with self._lock, self._conn() as c:
            c.execute(
                "UPDATE sessions SET ended_at = ?, status = 'completed' WHERE id = ?",
                (ts, session_id),
            )

    # --- read helpers (used by /api/capture endpoints) ---
    def stats(self) -> dict:
        with self._conn() as c:
            n_sess = c.execute("SELECT COUNT(*) FROM sessions").fetchone()[0]
            n_prompts = c.execute("SELECT COUNT(*) FROM prompts").fetchone()[0]
            n_active = c.execute("SELECT COUNT(*) FROM sessions WHERE status='active'").fetchone()[0]
            latest = c.execute(
                "SELECT id, project, started_at, first_prompt FROM sessions "
                "ORDER BY started_at DESC LIMIT 5"
            ).fetchall()
        return {
            "db_path": self.db_path,
            "sessions": n_sess,
            "prompts": n_prompts,
            "active": n_active,
            "latest": [dict(r) for r in latest],
        }

    def list_sessions(self, limit: int = 50) -> list[dict]:
        with self._conn() as c:
            rows = c.execute(
                "SELECT id, project, cwd, started_at, ended_at, status, "
                "       first_prompt, prompt_count, label, summary "
                "FROM sessions ORDER BY started_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [dict(r) for r in rows]

    # ----- Phase C helpers -----
    def get_session(self, session_id: str) -> Optional[dict]:
        with self._conn() as c:
            r = c.execute("SELECT * FROM sessions WHERE id = ?", (session_id,)).fetchone()
        return dict(r) if r else None

    def prompts_for(self, session_id: str, limit: int = 200) -> list[str]:
        with self._conn() as c:
            rows = c.execute(
                "SELECT text FROM prompts WHERE session_id = ? ORDER BY ts LIMIT ?",
                (session_id, limit),
            ).fetchall()
        return [r["text"] for r in rows]

    def set_session_clarification(self, session_id: str, label: Optional[str],
                                  summary: Optional[str]) -> None:
        with self._lock, self._conn() as c:
            c.execute(
                "UPDATE sessions SET label = COALESCE(?, label), summary = COALESCE(?, summary) "
                "WHERE id = ?",
                (label, summary, session_id),
            )

    def replace_observations(self, session_id: str, observations: list[dict]) -> int:
        """Drop existing observations for this session and insert the new ones.
        Each observation: {type, title, text, tags: [str]}."""
        now = int(time.time() * 1000)
        with self._lock, self._conn() as c:
            c.execute("DELETE FROM observations WHERE session_id = ?", (session_id,))
            for i, o in enumerate(observations):
                c.execute(
                    "INSERT INTO observations (session_id, ord, type, title, text, tags, created_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (
                        session_id, i,
                        (o.get("type") or "discovery").lower(),
                        (o.get("title") or "").strip()[:200],
                        (o.get("text") or "").strip(),
                        json.dumps(list(o.get("tags") or [])[:8]),
                        now,
                    ),
                )
            return len(observations)

    def observations_for(self, session_id: str) -> list[dict]:
        with self._conn() as c:
            rows = c.execute(
                "SELECT id, ord, type, title, text, tags, created_at "
                "FROM observations WHERE session_id = ? ORDER BY ord",
                (session_id,),
            ).fetchall()
        out = []
        for r in rows:
            d = dict(r)
            try:
                d["tags"] = json.loads(d["tags"] or "[]")
            except json.JSONDecodeError:
                d["tags"] = []
            out.append(d)
        return out

    def sessions_needing_observations(self, limit: int = 1000) -> list[str]:
        """For backfill: session ids that have prompts but no observations yet."""
        with self._conn() as c:
            rows = c.execute(
                "SELECT s.id FROM sessions s "
                "WHERE s.prompt_count > 0 "
                "  AND NOT EXISTS (SELECT 1 FROM observations o WHERE o.session_id = s.id) "
                "ORDER BY s.started_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [r["id"] for r in rows]

    def import_legacy_session(self, session_id: str, project: Optional[str],
                              started_at: int, first_prompt: Optional[str],
                              prompts: list[tuple[int, str]]) -> None:
        """Seed a session + its prompts from an external source (e.g. claude-mem).
        Used by the backfill so Phase C has real material to generate against
        before new sessions accumulate naturally."""
        with self._lock, self._conn() as c:
            c.execute(
                "INSERT OR IGNORE INTO sessions (id, project, started_at, status, first_prompt, prompt_count) "
                "VALUES (?, ?, ?, 'completed', ?, 0)",
                (session_id, project, started_at, first_prompt),
            )
            # Only insert prompts if this session has none yet (idempotent backfill)
            existing = c.execute(
                "SELECT COUNT(*) FROM prompts WHERE session_id = ?", (session_id,)
            ).fetchone()[0]
            if existing == 0 and prompts:
                c.executemany(
                    "INSERT INTO prompts (session_id, ts, text) VALUES (?, ?, ?)",
                    [(session_id, ts, text) for ts, text in prompts],
                )
                c.execute(
                    "UPDATE sessions SET prompt_count = ? WHERE id = ?",
                    (len(prompts), session_id),
                )
